# Generated by Django 4.1 on 2022-08-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prayersTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr', models.CharField(max_length=250)),
                ('sunrise', models.CharField(max_length=250)),
                ('duhur', models.CharField(max_length=250)),
                ('asr', models.CharField(max_length=250)),
                ('maghrib', models.CharField(max_length=250)),
                ('isha', models.CharField(max_length=250)),
                ('imsak', models.CharField(max_length=250)),
            ],
        ),
    ]
