# Generated by Django 4.1 on 2022-08-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerstime',
            name='midnight',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
