# Generated by Django 4.1 on 2022-08-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayersapp', '0004_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Species',
        ),
    ]
