# Generated by Django 4.1 on 2022-08-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayersapp', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
