# Generated by Django 4.1 on 2022-08-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayersapp', '0009_alter_prayerstime_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerstime',
            options={'verbose_name': 'PrayersTime', 'verbose_name_plural': 'PrayersTime'},
        ),
    ]
